spring:
  # This below configuration to enable the database connection with MySQL DB
  #datasource:
    #url: jdbc:mysql://localhost:3307/dev_schema?allowPublicKeyRetrieval=true&useSSL=false
    #username: jegadeesh
    #password: admin
  #jpa:
    #database-platform: org.hibernate.dialect.MySQL5Dialect
  # This below configuration to enable the liquibase database migration
  liquibase:
    enabled: true
    default-schema: dev_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml
