spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_schema
    username: jegadeesh
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    enabled: true
    default-schema: dev_schema
    change-log: classpath:db/changelog/db.changelog-master.yaml
